{ pkgs, ... }:


{
  home.packages = [
    pkgs.wlopm
    pkgs.wayshot
    pkgs.waybar
    pkgs.gnumake
    pkgs.wf-recorder
    pkgs.passage
    pkgs.bspwm
    pkgs.tmate
    pkgs.unclutter
    pkgs.tree
    pkgs.highlight
    pkgs.foot
    pkgs.evtest
    pkgs.agebox
    pkgs.go
    pkgs.obsidian
    pkgs.packer
    pkgs.scrcpy
    pkgs.slop
    pkgs.tamzen
    pkgs.termsyn
    pkgs.toilet
    pkgs.python3
    pkgs.swaybg
    pkgs.wev
    pkgs.rivercarro
    pkgs.htop
    pkgs.wofi
    #pkgs.swaylock # Use system swaylock instead...
    pkgs.waylock
    pkgs.yarn
    pkgs.glpaper
    pkgs.wlsunset
    pkgs.swayidle
    pkgs.android-tools
    pkgs.zsh
    pkgs.eksctl
    pkgs.kubectl
    pkgs.usb-modeswitch
    pkgs.lemonbar-xft
    pkgs._2bwm
    pkgs.recoll
    pkgs.anki
    pkgs.p7zip
    pkgs.zip
    pkgs.lua
    pkgs.kitty
    pkgs.alacritty
    pkgs.unzip
    pkgs.leafpad
    pkgs.river
    pkgs.stacktile
    pkgs.mpd
    pkgs.brightnessctl
    pkgs.xdo
    pkgs.mpc-cli
    pkgs.sxhkd
    pkgs.gnupg
    pkgs.pinentry-curses
    pkgs.fbida
    pkgs.dash
    pkgs.pamixer
    pkgs.picom
    pkgs.xss-lock
    pkgs.rofi
    pkgs.feh
    pkgs.mplayer
    pkgs.age
    pkgs.tig
    pkgs.termite
    pkgs.mpv
    pkgs.awesome
    pkgs.gcc
    pkgs.cmake
    pkgs.findimagedupes
    pkgs.meh
    pkgs.ffmpeg
    pkgs.xorg.xrandr
    pkgs.ffmpegthumbnailer
    pkgs.msmtp
    pkgs.notmuch
    pkgs.ranger
    pkgs.redshift
    pkgs.hugo
    pkgs.urlview
    pkgs.xorg.xev
    pkgs.xorg.xwininfo
    pkgs.xorg.xdpyinfo
    pkgs.xorg.xkill
    pkgs.xorg.xmodmap
    pkgs.xlsfonts
    pkgs.font-awesome
    pkgs.jq
    pkgs.youtube-dl
    pkgs.sxiv
    pkgs.libnotify
    pkgs.youtube-viewer
    pkgs.ueberzug
    pkgs.simplescreenrecorder
    pkgs.zsh-powerlevel10k
    pkgs.tmux
    pkgs.xdotool
    pkgs.xdo
    pkgs.asciinema
    pkgs.weechat
    pkgs.mutt
    pkgs.google-chrome
    pkgs.bc
    pkgs.fira
    pkgs.yaru-theme
    pkgs.element-desktop
    pkgs.zilla-slab
    pkgs.pciutils
    pkgs.playerctl
    pkgs.pass
    pkgs.pfetch
    pkgs.pavucontrol
    pkgs.tdesktop
    pkgs.isync
    pkgs.ponymix
    pkgs.stow
    pkgs.cmus
    pkgs.imagemagick
    pkgs.powerline-fonts
    pkgs.rxvt-unicode
    pkgs.powerline
    pkgs.nodejs
    pkgs.pipewire
    pkgs.virtualbox
    pkgs.fd
    pkgs.figlet
    pkgs.fq
    pkgs.gh
    pkgs.gitui
    pkgs.git
    pkgs.elinks
    pkgs.file
    pkgs.glow
    pkgs.lolcat
    pkgs.lr
    pkgs.ncdu
    pkgs.whois
    pkgs.xclip
    pkgs.xsel
    pkgs.moreutils
    pkgs.nix-index
    pkgs.nix-info
    pkgs.nix-top
    pkgs.nixfmt
    pkgs.nixpkgs-fmt
    pkgs.wl-clipboard
    pkgs.polybarFull
    pkgs.mako
  ];
}
