{ pkgs, ... }:

{
  home.packages = [
    #pkgs.wlopm
    pkgs.wayshot
    pkgs.waybar
    pkgs.gnumake
    pkgs.wf-recorder
    pkgs.passage
    #pkgs.bspwm
    pkgs.tmate
    #pkgs.unclutter
    pkgs.tree
    pkgs.highlight
    #pkgs.foot
    #pkgs.evtest
    pkgs.agebox
    #pkgs.go
    pkgs.mp3info
    #pkgs.obsidian
    #pkgs.packer
    pkgs.scrcpy
    #pkgs.slop
    pkgs.tamzen
    pkgs.termsyn
    pkgs.toilet
    pkgs.python3
    pkgs.slack
    pkgs.swaybg
    pkgs.wev
    pkgs.rivercarro
    pkgs.htop
    pkgs.vagrant
    pkgs.wofi
    #pkgs.swaylock # Use system swaylock instead...
    #pkgs.gns3-gui
    #pkgs.gns3-server
    pkgs.unrar
    pkgs.ansible
    #pkgs.discord
    #pkgs.yarn
    pkgs.glpaper
    pkgs.python310Packages.pip
    #pkgs.wlsunset
    pkgs.swayidle
    pkgs.helvum
    pkgs.wl-color-picker
    pkgs.android-tools
    pkgs.zathura
    pkgs.zsh
    pkgs.eksctl
    pkgs.kubectl
    pkgs.usb-modeswitch
    #pkgs.lemonbar-xft
    pkgs.recoll
    #pkgs.anki
    pkgs.p7zip
    pkgs.zip
    #pkgs.lua
    #pkgs.kitty
    pkgs.alacritty
    pkgs.unzip
    #pkgs.leafpad
    pkgs.river
    pkgs.stacktile
    pkgs.mpd
    pkgs.mpc-cli
    pkgs.gtypist
    #pkgs.brightnessctl
    #pkgs.xdo
    #pkgs.sxhkd
    #pkgs.zoom-us
    pkgs.gnupg
    pkgs.pinentry-curses
    pkgs.fbida
    pkgs.dash
    pkgs.pamixer
    #pkgs.picom
    #pkgs.xss-lock
    #pkgs.rofi
    pkgs.feh
    #pkgs.mplayer
    pkgs.age
    pkgs.tig
    #pkgs.termite
    pkgs.mpv
    #pkgs.awesome
    #pkgs.gcc
    #pkgs.cmake
    pkgs.findimagedupes
    pkgs.meh
    pkgs.ffmpeg_5-full
    #pkgs.xorg.xrandr
    pkgs.ffmpegthumbnailer
    pkgs.msmtp
    pkgs.notmuch
    pkgs.ranger
    pkgs.hugo
    pkgs.nafees
    pkgs.opera
    pkgs.urlview
    #pkgs.xorg.xev
    #pkgs.xorg.xwininfo
    #pkgs.xorg.xdpyinfo
    #pkgs.xorg.xkill
    #pkgs.xorg.xmodmap
    pkgs.bear
    #pkgs.xlsfonts
    pkgs.font-awesome
    pkgs.jq
    pkgs.youtube-dl
    pkgs.sxiv
    pkgs.libnotify
    pkgs.youtube-viewer
    pkgs.ueberzug
    #pkgs.simplescreenrecorder
    #pkgs.zsh-powerlevel10k
    pkgs.tmux
    #pkgs.xdotool
    #pkgs.xdo
    pkgs.asciinema
    pkgs.weechat
    pkgs.neomutt
    pkgs.goimapnotify
    pkgs.keychain
    pkgs.google-chrome
    pkgs.strace
    pkgs.bc
    pkgs.fira
    #pkgs.yaru-theme
    pkgs.dracula-theme
    pkgs.slurp
    pkgs.element-desktop
    pkgs.zilla-slab
    pkgs.pciutils
    #pkgs.playerctl
    pkgs.pfetch
    pkgs.pavucontrol
    pkgs.bat
    pkgs.sops
    #pkgs.tdesktop # telegram
    pkgs.isync
    #pkgs.ponymix
    #pkgs.stow
    pkgs.cmus
    pkgs.imagemagick
    pkgs.powerline-fonts
    pkgs.meslo-lg
    #pkgs.hyprland
    #pkgs.hyprpaper
    pkgs.rxvt-unicode
    pkgs.go
    pkgs.gotools
    pkgs.powerline
    pkgs.nodejs
    pkgs.sd
    pkgs.pipewire
    pkgs.xterm
    pkgs.pwgen
    pkgs.inetutils
    pkgs.fd
    pkgs.figlet
    pkgs.fq
    pkgs.git-filter-repo
    pkgs.elinks
    pkgs.file
    pkgs.jetbrains-mono
    pkgs.glow
    pkgs.lolcat
    pkgs.lr
    #pkgs.ncdu
    #pkgs.xclip
    #pkgs.teamviewer
    #pkgs.anydesk
    pkgs.usbutils
    #pkgs.xsel
    pkgs.moreutils
    pkgs.nix-index
    pkgs.nix-info
    pkgs.nix-top
    pkgs.nixfmt
    pkgs.nixpkgs-fmt
    pkgs.wl-clipboard
    #pkgs.polybarFull
    pkgs.mako
  ];
}
